# Generated by Django 5.2.5 on 2025-09-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('transactions_type', models.CharField(choices=[('A', 'Add Stock'), ('S', 'Sale'), ('R', 'Return')], max_length=2)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.products')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.sellers')),
            ],
        ),
    ]
