# Generated by Django 5.2.5 on 2025-09-03 11:24

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ManyToManyField(to='inventoryapp.sellers'),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('transactions_type', models.CharField(choices=[('P', 'Purchase'), ('S', 'Sale'), ('R', 'Return')], max_length=2)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('price_per_unit')), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.products')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.sellers')),
            ],
        ),
    ]
