# Generated by Django 5.2.5 on 2025-09-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0004_sellers_products_quantity_in_stock_products_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.category'),
        ),
    ]
