# Generated by Django 5.2.5 on 2025-09-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0005_transactions_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='category',
        ),
    ]
